// Embed the application icon into the Windows executable so Explorer, the
// pinned taskbar entry, and the Start Menu shortcut show the real icon instead
// of the generic Windows default. `assets/twocents.ico` is a committed artifact
// generated by `tools/gen_icon.py`.
fn main() {
    println!("cargo:rerun-if-changed=assets/twocents.ico");
    println!("cargo:rerun-if-changed=build.rs");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/twocents.ico");
        if let Err(err) = res.compile() {
            println!("cargo:warning=failed to embed the application icon: {err}");
        }
    }
}
